
name: .NET Core Desktop

on:
  push:
    tags:
    - '*'

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: .\\src\\TEdit.sln
      Publish_Path: .\\src\\TEdit\\bin\\Release\\net462\\publish
      File_Name: TEdit_${{github.ref_name}}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
    # Create the app package by building and packaging the Windows Application Packaging project

    - name: Create the app package
    - uses: ncipollo/release-action@v1
      with: 
        artifacts: "./release/*.zip"
      run: >
        dotnet publish -c Release $env:Solution_Name
        Copy-Item -Path $env:Publish_Path -Destination ".\release\${$env:File_Name}\" -Recurse -Force
        Copy-Item -Path ".\schematics" -Destination ".\release" -Recurse
        Compress-Archive -Path ".\release\*" -DestinationPath ".\${$env:File_Name}.zip"
      env:
        Configuration: ${{ matrix.configuration }}
